input("Press Enter to get started with Task#01")
print("")
print("")
print("Twinkle Twinkle little star,\n      How i wonder what you are!")
print("        Up above the world so high\n        Like the diamond in the sky.")
print("Twinkle Twinkle little star,\n      How i wonder what you are!")
print("")
print("")
input("Hit the Enter key to get out !\nThank You!")
