import sys
input("Press Enter key to get started with task#02")
print("")
print("PYTHON VERSION:\n")
print(sys.version)
print("")
print("\nVERSION INFORMATION:\n")
print(sys.version_info)
print("")
print("")
input("Hit the Enter key to get out!\nTHANK YOU!")
